import { UserProvider } from "@/contexts/UserContext";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "./reset.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full m-0 p-0">
      <body className={montserrat.className}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
